config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from .views import home_page

app_name = 'home'

urlpatterns = [
    path('', home_page, name='home'),
]

products/urls.py
from django.urls import path
from .views import (
    BookListView, BookDetailView, BookUpdateView,
    BookCreateView, AddReviewView, BookDeleteView,
    DeleteReviewView, UpdateReviewView)


app_name = 'products'

urlpatterns = [
    path('book-list/',  BookListView.as_view(), name='book-list'),
    path('book-detail/<int:pk>/', BookDetailView.as_view(), name='book-detail'),
    path('book-update/<int:pk>/', BookUpdateView.as_view(), name='book-update'),
    path('book-create/', BookCreateView.as_view(), name='book-create'),
    path('book-delete/<int:pk>/', BookDeleteView.as_view(), name='book-delete'),
    path('add-review/<int:pk>/', AddReviewView.as_view(), name='add-review'),
    path('update-review/<int:pk>/', UpdateReviewView.as_view(), name='update-review'),
    path('delete-review/<int:pk>/', DeleteReviewView.as_view(), name='delete-review')
]

products/models.py
from django.db import models
from users.models import Users
from django.core.validators import MinValueValidator, MaxValueValidator


class CategoryBooks(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        db_table = 'category'

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'language'

    def __str__(self):
        return self.name


class Books(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    category = models.ForeignKey(CategoryBooks, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='books/', default='default_img/download.jpg')
    page = models.IntegerField()
    book_lang = models.ForeignKey(Language, on_delete=models.DO_NOTHING)

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    class Meta:
        db_table = 'books'

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    class Meta:
        db_table = 'author'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class BookAuthor(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    class Meta:
        db_table = 'book_author'

    def __str__(self):
        return f'{self.book.title} - {self.author.first_name} {self.author.last_name}'


class Review(models.Model):
    comment = models.CharField(max_length=200)
    star_given = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0)
        ]
     )
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    user = models.ForeignKey(Users, on_delete=models.CASCADE)

    class Meta:
        db_table ='review'

    def __str__(self):
        return f'{self.star_given} - {self.book.title} - {self.user.username}'

products/forms.py
from django.forms import ModelForm
from django import forms
from .models import Review, Books


class BookForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = ['title', 'description', 'price', 'category', 'page', 'image', 'book_lang']


class AddReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment', 'star_given']


# class BookForm(forms.ModelForm):
#     class Meta:
#         model = Books
#         fields = ['title', 'description', 'price', 'category', 'page', 'image', 'book_lang']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment', 'star_given']

products/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from .forms import AddReviewForm, ReviewForm
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Books, Review
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView,CreateView, DeleteView
from .forms import BookForm
from django.contrib import messages


class BookListView(View):
    def get(self, request):
        book = Books.objects.all().order_by('-id')
        context = {
            'book': book
        }
        return render(request, 'book_list.html', context=context)


# class BookDetailView(View):
#     def get(self, request, pk):
#         book = Books.objects.get(pk=pk)
#         reviews = Review.objects.filter(book=pk)
#         context = {
#             'book': book,
#             'reviews': reviews
#         }
#         return render(request, 'book_detail.html', context=context)


class BookDetailView(View):
    @method_decorator(login_required)
    def get(self, request, pk):
        book = get_object_or_404(Books, pk=pk)
        reviews = Review.objects.filter(book=pk)
        user_has_reviewed = reviews.filter(user=request.user).exists()
        context = {
            'book': book,
            'reviews': reviews,
            'current_user': request.user,
            'user_has_reviewed': user_has_reviewed,
        }
        return render(request, 'book_detail.html', context=context)


class BookUpdateView(LoginRequiredMixin, View):
    def get(self, request, pk):
        book = get_object_or_404(Books, pk=pk)
        form = BookForm(instance=book)
        context = {
            'form': form
        }
        return render(request, 'update.html', context=context)

    def post(self, request, pk):
        book = get_object_or_404(Books, pk=pk)
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect('products:book-detail', pk=pk)
        else:
            context = {
                'form': form
            }
            return render(request, 'update.html', context=context)


class BookCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = BookForm()
        context = {
            'form': form
        }
        return render(request, 'book_create.html', context=context)

    def post(self, request):
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            new_book = form.save(commit=False)
            new_book.save()
            return redirect('products:book-list')
        else:
            return render(request, 'book_create.html', {'form': form})


class BookDeleteView(LoginRequiredMixin, DeleteView):
    model = Books
    template_name = 'book_delete.html'
    success_url = reverse_lazy('products:book-list')

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Books, pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Delete book'
        return context


class AddReviewView(LoginRequiredMixin, View):
    def get(self, request, pk):
        book = get_object_or_404(Books, pk=pk)
        add_review_form = AddReviewForm()
        context = {
            'book': book,
            'add_review_form': add_review_form
        }
        return render(request, 'add_review.html', context=context)

    def post(self, request, pk):
        book = get_object_or_404(Books, pk=pk)
        add_review_form = AddReviewForm(request.POST)
        if add_review_form.is_valid():
            review = add_review_form.save(commit=False)
            review.book = book
            review.user = request.user
            review.save()
            messages.success(request, 'Review added successfully!')
            return redirect('products:book-detail', pk=pk)
        else:
            messages.error(request, 'Something went wrong. Please check your input.')
            context = {
                'book': book,
                'add_review_form': add_review_form
            }
            return render(request, 'add_review.html', context=context)


class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, pk):
        review = get_object_or_404(Review, pk=pk)
        is_author = review.user == request.user
        return render(request, 'delete_review.html', {'review': review, 'is_author': is_author})

    def post(self, request, pk):
        review = get_object_or_404(Review, pk=pk)
        if review.user != request.user:
            messages.error(request, "You are not authorized to delete this review.")
            return redirect('products:book-detail', pk=review.book_id)

        review.delete()
        messages.success(request, 'Review deleted successfully.')
        return redirect('products:book-detail', pk=review.book_id)


# class DeleteReviewView(DeleteView):
#     model = Review
#     success_url = reverse_lazy('products:book-list')
#
#     def get_success_url(self):
#         # Assuming you have a ForeignKey relationship from Review to Book
#         book_pk = self.object.book.pk
#         return reverse_lazy('products:book-detail', kwargs={'pk': book_pk})


class UpdateReviewView(LoginRequiredMixin, View):
    def get(self, request, pk):
        review = get_object_or_404(Review, pk=pk)
        form = AddReviewForm(instance=review)
        context = {
            'form': form,
            'review': review
        }
        return render(request, 'update_review.html', context=context)

    def post(self, request, pk):
        review = get_object_or_404(Review, pk=pk)
        form = AddReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            messages.success(request, 'Review updated successfully.')
            return redirect('products:book-detail', pk=review.book_id)
        else:
            messages.error(request, 'Error updating review. Please check the form.')
        return render(request, 'update_review.html', {'form': form, 'review': review})

products/templates/add_review.html
{% extends 'base.html' %}

{% block title %}
    add review
{% endblock title %}

{% block content %}
    <style>
        /* Apply styles to the container */
        .container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }

        /* Apply styles to headings */
        h1 {
            color: #333;
            margin-bottom: 20px;
        }

        /* Apply styles to the form */
        form {
            margin-bottom: 20px;
        }

        /* Apply styles to form elements */
        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            width: auto;
        }

        input[type="submit"]:hover {
            background-color: #0056b3;
        }

        /* Apply styles to messages */
        .messages {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .messages li {
            margin-bottom: 10px;
            color: #dc3545; /* Red color for error messages */
        }
    </style>

    <div class="container">
        <h1>{{ books.title }}</h1>
        <form method="post">
            {% csrf_token %}
            {{ add_review_form.as_p }}
            <input type="submit" value="Add Review">
        </form>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
{% endblock content %}

products/templates/book_create.html
{% extends 'base.html' %}

{% block title %}
    Create Book
{% endblock title %}

{% block content %}
    <style>
        /* Apply styles to the form container */
        .form-container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }

        /* Apply styles to form elements */
        form {
            display: flex;
            flex-direction: column;
        }

        label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="number"],
        textarea {
            padding: 10px;
            margin-bottom: 15px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }

        input[type="submit"] {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>

    <div class="form-container">
        <h1>Create Book</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    </div>
{% endblock content %}

products/templates/book_delete.html
{% extends 'base.html' %}

{% block title %}
    book delete
{% endblock title %}

{% block content %}
    <style>
        /* Apply styles to the confirmation message */
        .confirmation-message {
            font-size: 18px;
            margin-bottom: 20px;
        }

        /* Apply styles to the form container */
        .container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }

        /* Apply styles to the submit button */
        input[type="submit"] {
            padding: 10px 20px;
            background-color: #dc3545;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            width: auto; /* Adjust width to fit content */
        }

        /* Apply styles to the cancel button */
        button {
            background-color: transparent;
            border: none;
            cursor: pointer;
        }

        a.no-link {
            color: #007bff;
            text-decoration: none;
        }
    </style>

    <div class="container">
        <p class="confirmation-message">Are you sure you want to delete "{{ object }}"?</p>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="Confirm">
        </form>
        <button><a href="{% url 'products:book-detail' object.pk  %}" class="no-link">Cancel</a></button>
    </div>
{% endblock content %}

products/templates/book_detail.html
{% extends 'base.html' %}

{% block title %}
    home page
{% endblock title %}

{% block content %}
    <style>
        /* Apply general styles to the content wrapper */
        .content-wrapper {
            margin: 20px;
        }

        /* Apply styles to the book details container */
        .book-details-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        /* Apply styles to headings */
        h1 {
            color: #333;
        }

        /* Apply styles to links */
        a {
            color: #007bff;
            text-decoration: none;
            padding: 8px 12px;
            border-radius: 5px;
        }

        a.delete-link {
            background-color: #dc3545;
            color: #fff;
        }

        a.add-review-link {
            background-color: #007bff;
            color: #fff;
        }

        /* Apply styles to review items */
        .review-item {
            margin-top: 20px;
            border: 1px solid #ccc;
            padding: 10px;
            border-radius: 5px;
        }

        /* Apply styles to edit and delete buttons */
        .btn {
            text-decoration: none;
            padding: 5px 10px;
            border-radius: 5px;
        }

        .btn-warning {
            background-color: #ffc107;
            color: #fff;
        }

        .btn-danger {
            background-color: #dc3545;
            color: #fff;
        }
    </style>
    <div class="content-wrapper">
    <div class="book-details-container">
        <h1>Name: {{ book.title }}</h1>
        <img src="{{ book.image.url }}" alt="Book Image" height="200px"><br><br>
        <h4>Description: {{ book.description }}</h4>
        <h4>Price: {{ book.price }}</h4>
        <h4>Pages: {{ book.page }}</h4>
        <a href="{% url 'products:book-delete' pk=book.pk %}" class="delete-link">Delete</a>
        <h2>Reviews</h2>
        <a href="{% url 'products:book-update' book.pk %}" class="add-review-link">Update</a> <br><br>
        {% if not user_has_reviewed %}
        <a href="{% url 'products:add-review' book.pk %}" class="btn btn-primary">Add Review</a><br><br>
        {% endif %}

        {% for review in reviews %}
        <div class="review-item">
            <h4>{{ review.user.username }} | {{ review.star_given }}</h4>
            <p>{{ review.comment }}</p> <br>
            {% if review.user == current_user %}
            <div>
                <a href="{% url 'products:update-review' pk=review.pk %}" class="btn btn-warning">Edit</a>
                <a href="{% url 'products:delete-review' pk=review.pk %}" class="btn btn-danger">Delete</a>
            </div>
            {% endif %}
        </div>
        {% endfor %}

    </div>
</div>
{% endblock content %}

products/templates/book_list.html
{% extends 'base.html' %}

{% block title %}
    Books
{% endblock title %}

{% block content %}
<style>
    /* Apply general styles to the books container */
    .books-container {
        width: 80%;
        margin: 20px auto;
        padding: 20px;
        background-color: #f9f9f9;
        border-radius: 10px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    }

    /* Apply styles to headings */
    h1 {
        color: #333;
        margin-bottom: 20px;
    }

    /* Apply styles to links */
    a {
        color: #007bff;
        text-decoration: none;
        padding: 8px 12px;
        border-radius: 5px;
    }

    /* Apply styles to the "Add Book" link */
    .add-book-link {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        text-align: center;
        border-radius: 5px;
        transition: background-color 0.3s ease;
    }

    .add-book-link:hover {
        background-color: #0056b3;
    }

    /* Apply styles to book links */
    .book-link {
        display: block;
        margin-bottom: 10px;
        padding: 10px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        transition: box-shadow 0.3s ease;
    }

    .book-link:hover {
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
    }
</style>

    <div class="books-container">
        <h1>Books Page</h1>
        <a href="{% url 'products:book-create' %}" class="add-book-link">Add Book</a>
        <hr>
        {% for b in book %}
            <a href="{% url 'products:book-detail' b.pk %}" class="book-link">{{ b.title }}</a>
        {% endfor %}
    </div>
{% endblock content %}

products/templates/delete_review.html
{% extends 'base.html' %}

{% block title %}
    Delete Review
{% endblock title %}

{% block content %}
    <style>
        /* Apply styles to the container */
        .container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }

        /* Apply styles to the confirmation message */
        .confirmation-message {
            margin-bottom: 20px;
        }

        /* Apply styles to the form */
        form {
            margin-bottom: 20px;
        }

        /* Apply styles to the submit button */
        input[type="submit"] {
            padding: 10px 20px;
            background-color: #dc3545;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            width: auto;
        }

        input[type="submit"]:hover {
            background-color: #c82333;
        }

        /* Apply styles to the cancel button */
        .no-link {
            color: #007bff;
            text-decoration: none;
            padding: 8px 12px;
            border-radius: 5px;
            background-color: #f8f9fa;
        }

        .no-link:hover {
            background-color: #e2e6ea;
        }
    </style>

    <div class="container">
        <p class="confirmation-message">Are you sure you want to delete "{{ object }}"?</p>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="Confirm">
        </form>
        <a href="{% url 'products:book-detail' pk=review.book.pk %}" class="no-link">Cancel</a>
    </div>
{% endblock content %}

products/templates/update.html
{% extends 'base.html' %}

{% block title %}
    update book
{% endblock title %}

{% block content %}
    <style>
        /* Apply styles to the form container */
        form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }

        /* Apply styles to the form elements */
        input[type="text"],
        input[type="file"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }

        /* Apply styles to the submit button */
        button[type="submit"] {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            width: auto;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
{% endblock content %}

products/templates/update_review.html
{% extends 'base.html' %}

{% block title %}
    update review
{% endblock title %}

{% block content %}
    <style>
        /* Apply styles to the container */
        .container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }

        /* Apply styles to headings */
        h1 {
            color: #333;
            margin-bottom: 20px;
        }

        /* Apply styles to the form */
        form {
            margin-bottom: 20px;
        }

        /* Apply styles to form elements */
        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            width: auto;
        }

        input[type="submit"]:hover {
            background-color: #0056b3;
        }

        /* Apply styles to messages */
        .messages {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .messages li {
            margin-bottom: 10px;
            color: #dc3545; /* Red color for error messages */
        }
    </style>

    <div class="container">
        <h1>{{ books.title }}</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update Review">
        </form>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
{% endblock content %}